# flake8: noqa
# Generated by Django 3.2.3 on 2021-05-23 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='permission',
        ),
        migrations.AlterField(
            model_name='issue',
            name='desc',
            field=models.CharField(blank=True, max_length=4095, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='author_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
