# Generated by Django 3.2.3 on 2021-05-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210523_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('0', False), ('1', True)], default='0', max_length=15),
            preserve_default=False,
        ),
    ]
