# Generated by Django 3.2.3 on 2021-05-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_projet_id_issue_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(default='done', max_length=50),
            preserve_default=False,
        ),
    ]
